export const EVENT_TYPES = {
  START_TIME_ANALYSIS: "START_TIME_ANALYSIS",
  STOP_TIME_ANALYSIS: "STOP_TIME_ANALYSIS",
  START_SPACE_ANALYSIS: "START_SPACE_ANALYSIS",
  STOP_SPACE_ANALYSIS: "STOP_SPACE_ANALYSIS",
  NEW_TIME_MARK: "NEW_TIME_MARK",
  TIME_ANALYSIS_COMPLETE: "TIME_ANALYSIS_COMPLETE",
  SPACE_ANALYSIS_COMPLETE: "SPACE_ANALYSIS_COMPLETE",
};

export const DEFAULT_ITERATIONS = 50;
